import type { Track, Creator } from '@/types';

export const TRACKS: Track[] = [
  {
    id: '1',
    title: 'Midnight Frequencies',
    artist: 'DJ Nova',
    artistId: '1',
    artistSlug: 'dj-nova',
    genre: 'House',
    bpm: 128,
    duration: '4:32',
    plays: 2847,
    rating: 4.7,
    ratingCount: 189,
    cover: '🌙',
    waveColor: '#8B5CF6',
  },
  {
    id: '2',
    title: 'Neon Pulse Rework',
    artist: 'Synthwave Kid',
    artistId: '2',
    artistSlug: 'synthwave-kid',
    genre: 'Synthwave',
    bpm: 110,
    duration: '3:58',
    plays: 1923,
    rating: 4.3,
    ratingCount: 134,
    cover: '⚡',
    waveColor: '#EC4899',
  },
  {
    id: '3',
    title: 'Bass Cathedral',
    artist: 'LowFreq',
    artistId: '3',
    artistSlug: 'lowfreq',
    genre: 'DnB',
    bpm: 174,
    duration: '5:11',
    plays: 4102,
    rating: 4.9,
    ratingCount: 301,
    cover: '🔊',
    waveColor: '#06B6D4',
  },
  {
    id: '4',
    title: 'Tokyo Drift Edit',
    artist: 'DJ Nova',
    artistId: '1',
    artistSlug: 'dj-nova',
    genre: 'Techno',
    bpm: 138,
    duration: '6:03',
    plays: 3561,
    rating: 4.5,
    ratingCount: 228,
    cover: '🗼',
    waveColor: '#F59E0B',
  },
  {
    id: '5',
    title: 'Velvet Underground Mix',
    artist: 'Deepstate',
    artistId: '4',
    artistSlug: 'deepstate',
    genre: 'Deep House',
    bpm: 122,
    duration: '7:20',
    plays: 1587,
    rating: 4.6,
    ratingCount: 97,
    cover: '🎭',
    waveColor: '#10B981',
  },
  {
    id: '6',
    title: 'Broken Symmetry',
    artist: 'Glitchform',
    artistId: '5',
    artistSlug: 'glitchform',
    genre: 'IDM',
    bpm: 145,
    duration: '4:47',
    plays: 892,
    rating: 4.8,
    ratingCount: 76,
    cover: '💎',
    waveColor: '#F43F5E',
  },
];

export const CREATORS: Creator[] = [
  {
    id: '1',
    name: 'DJ Nova',
    slug: 'dj-nova',
    tracks: 24,
    followers: 1289,
    avatar: '🎧',
    accent: '#8B5CF6',
  },
  {
    id: '2',
    name: 'Synthwave Kid',
    slug: 'synthwave-kid',
    tracks: 18,
    followers: 856,
    avatar: '🌊',
    accent: '#EC4899',
  },
  {
    id: '3',
    name: 'LowFreq',
    slug: 'lowfreq',
    tracks: 31,
    followers: 2103,
    avatar: '🎵',
    accent: '#06B6D4',
  },
  {
    id: '4',
    name: 'Deepstate',
    slug: 'deepstate',
    tracks: 15,
    followers: 634,
    avatar: '🌀',
    accent: '#10B981',
  },
  {
    id: '5',
    name: 'Glitchform',
    slug: 'glitchform',
    tracks: 9,
    followers: 421,
    avatar: '✨',
    accent: '#F43F5E',
  },
];

export const GENRES: string[] = [
  'All',
  ...new Set(TRACKS.map((track) => track.genre)),
];