import type { Track, Creator } from '@/types';

export const TRACKS: Track[] = [
  {
    id: '1',
    title: 'Midnight Frequencies',
    artist: 'DJ Nova',
    artistId: '1',
    artistSlug: 'dj-nova',
    genre: 'House',
    bpm: 128,
    duration: '4:32',
    plays: 2847,
    rating: 4.7,
    ratingCount: 189,
    downloads: 342,
    cover: '🌙',
    waveColor: '#8B5CF6',
    uploadedAt: '2024-12-01',
  },
  {
    id: '2',
    title: 'Neon Pulse Rework',
    artist: 'Synthwave Kid',
    artistId: '2',
    artistSlug: 'synthwave-kid',
    genre: 'Synthwave',
    bpm: 110,
    duration: '3:58',
    plays: 1923,
    rating: 4.3,
    ratingCount: 134,
    downloads: 198,
    cover: '⚡',
    waveColor: '#EC4899',
    uploadedAt: '2024-11-15',
  },
  {
    id: '3',
    title: 'Bass Cathedral',
    artist: 'LowFreq',
    artistId: '3',
    artistSlug: 'lowfreq',
    genre: 'DnB',
    bpm: 174,
    duration: '5:11',
    plays: 4102,
    rating: 4.9,
    ratingCount: 301,
    downloads: 521,
    cover: '🔊',
    waveColor: '#06B6D4',
    uploadedAt: '2025-01-08',
  },
  {
    id: '4',
    title: 'Tokyo Drift Edit',
    artist: 'DJ Nova',
    artistId: '1',
    artistSlug: 'dj-nova',
    genre: 'Techno',
    bpm: 138,
    duration: '6:03',
    plays: 3561,
    rating: 4.5,
    ratingCount: 228,
    downloads: 489,
    cover: '🗼',
    waveColor: '#F59E0B',
    uploadedAt: '2024-10-20',
  },
  {
    id: '5',
    title: 'Velvet Underground Mix',
    artist: 'Deepstate',
    artistId: '4',
    artistSlug: 'deepstate',
    genre: 'Deep House',
    bpm: 122,
    duration: '7:20',
    plays: 1587,
    rating: 4.6,
    ratingCount: 97,
    downloads: 167,
    cover: '🎭',
    waveColor: '#10B981',
    uploadedAt: '2024-09-03',
  },
  {
    id: '6',
    title: 'Broken Symmetry',
    artist: 'Glitchform',
    artistId: '5',
    artistSlug: 'glitchform',
    genre: 'IDM',
    bpm: 145,
    duration: '4:47',
    plays: 892,
    rating: 4.8,
    ratingCount: 76,
    downloads: 143,
    cover: '💎',
    waveColor: '#F43F5E',
    uploadedAt: '2025-01-20',
  },
];

export const CREATORS: Creator[] = [
  {
    id: '1',
    name: 'DJ Nova',
    slug: 'dj-nova',
    tracks: 24,
    followers: 1289,
    avatar: '🎧',
    accent: '#8B5CF6',
    bio: 'Productor house y techno con raíces en el underground europeo. Explorando los límites del ritmo desde 2015. Residente en Buenos Aires.',
    totalPlays: 6408,
    email: 'djnova@remixhub.io',
    instagram: 'djnova',
    youtube: 'DJNovaOfficial',
    website: 'https://djnova.link',
  },
  {
    id: '2',
    name: 'Synthwave Kid',
    slug: 'synthwave-kid',
    tracks: 18,
    followers: 856,
    avatar: '🌊',
    accent: '#EC4899',
    bio: 'Nostálgico de los 80s atrapado en el futuro. Sintetizadores analógicos, líneas de bajo gruesas y esa sensación de conducir de noche con luces de neón.',
    totalPlays: 1923,
    instagram: 'synthwavekid',
    website: 'https://linktr.ee/synthwavekid',
  },
  {
    id: '3',
    name: 'LowFreq',
    slug: 'lowfreq',
    tracks: 31,
    followers: 2103,
    avatar: '🎵',
    accent: '#06B6D4',
    bio: 'Sub-bass worshipper. Drum & Bass, Jungle, Neurofunk. Cada track es un viaje desde el suelo hasta el sistema nervioso central.',
    totalPlays: 4102,
    email: 'lowfreq@bass.io',
    instagram: 'lowfreq.dj',
    youtube: 'LowFreqBass',
  },
  {
    id: '4',
    name: 'Deepstate',
    slug: 'deepstate',
    tracks: 15,
    followers: 634,
    avatar: '🌀',
    accent: '#10B981',
    bio: 'Deep house y electrónica ambiental. Músicas para los momentos en que el tiempo se estira y el espacio se expande.',
    totalPlays: 1587,
    instagram: 'deepstate.music',
    website: 'https://deepstate.bandcamp.com',
  },
  {
    id: '5',
    name: 'Glitchform',
    slug: 'glitchform',
    tracks: 9,
    followers: 421,
    avatar: '✨',
    accent: '#F43F5E',
    bio: 'IDM, glitch y microtonalidad. El error como arte. La disonancia como hogar. Anti-groove.',
    totalPlays: 892,
    email: 'hello@glitchform.net',
    youtube: 'GlitchformIDM',
    website: 'https://glitchform.net',
  },
];

export const GENRES: string[] = [
  'All',
  ...new Set(TRACKS.map((track) => track.genre)),
];